name: "HxGN OnCall Wiki"
source_type: "azdo_wiki"
enabled: true
weight: 1.2
context_tags: ["documentation", "oncall", "zur", "wiki"]

config:
  organization: "HxGN-SI-ZUR"
  project: "HxGN OnCall"
  auth_type: "pat"
  pat: "REDACTED_PAT_HXGN_WIKI"
  use_incremental_sync: true
  included_wikis: ["Wiki.SG", "Wiki.VS"]
  enable_auto_summarization: true