# IntergraphOnCallAdministrator Web Help Instance
name: "IntergraphOnCallAdministrator"
source_type: "oncall_web_help"
enabled: false
weight: 1.0
config:
  folder_path: "data/sources/oncall_web_help/IntergraphOnCallAdministrator"
  options:
    file_extensions: [".html", ".htm"]
    recursive: true